### ISSUE TITLE
imdb one more time stop working

### ISSUE THREAD

**Issue by lyarinet** [dhobi/PHP-IMDb-Scraper#12]
im using codeigniter  PHP-IMDb-Scraper

some change private to public its work now but this time is not working 

private function scrapeMovieInfo($imdbUrl, $getExtraInfo = true)

public function scrapeMovieInfo($imdbUrl, $getExtraInfo = true)

**Comment by dhobi** [comment]
I don’t understand. Could you try to rephrase your question / issue description?

**Comment by lyarinet** [comment]
dear i mean im using PHP-IMDb-Scraper on codeigniter framework

and php-imdb-scraper not working on

wen im change  this line it's working 
private function scrapeMovieInfo($imdbUrl, $getExtraInfo = true)
to 
public function scrapeMovieInfo($imdbUrl, $getExtraInfo = true)
it's working 
but today is stop working

**Comment by dhobi** [comment]
I have no experience with codeigniter framework. Just a few things though:
- if codeigniter requires a public function, use the newly added „getMovieInfoByUrl“ instead of changing the code. It‘s already public and does the same thing.
- I doubt your issue has something to do with the php-imdb-scraper. Maybe it is a wrong imdb url or curl stopped working. Check your error logs / debug the code to get more information.

**Comment by dhobi** [comment]
No updates. Closed.
